# AWS
app.code=cpd
aws.region=us-east-1
aws.s3.bucket=
aws.sqs.queue.url=
aws.lambda.function.name=
aws.glue.database=

# Spark
spark.app.name=cpd-app
spark.master=local[2]
spark.warehouse.path=tmp/warehouse

# Iceberg
iceberg.catalog.name=local
iceberg.namespace=cpd
